---
- include: compat.yml

- include: include_vars.yml

- include: get_key_nodesource.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

# - include: RHEL.yml
#   when: >
#     ansible_distribution == 'CentOS' or
#     ansible_distribution == 'Red Hat Enterprise Linux'

- include: install_package_names.yml

- name: ensure config directory exists
  file:
    path: /etc/mediawiki/parsoid
    state: directory

- template:
    src: config.yaml.j2
    dest: /etc/mediawiki/parsoid/config.yaml
